# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Build docs
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install mkdocs
      run: |
          pip install mkdocs mkdocs-material mkdocs-redirects mkdocs-git-revision-date-localized-plugin
          mkdocs --version
    - name: build
      run: mkdocs build
    - name: deploy
      uses: 'JamesIves/github-pages-deploy-action@4.1.3'
      with:
        branch: gh-pages
        folder: docs

